name: Build extension

on: push

jobs:
  build:
    # Name the Job
    name: Build the extension artifact
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Set up jdk 12
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '12'
      - name: Build with maven wrapper
        run: ./mvnw clean install

